"""baseline - existing schema

Revision ID: daaa8d00a6a3
Revises: 
Create Date: 2026-07-04 16:05:15.224705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaa8d00a6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_submitted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_submission_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('test_approved_by_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_approval_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_approval_date')
        batch_op.drop_column('test_approved_by_admin')
        batch_op.drop_column('test_submission_date')
        batch_op.drop_column('test_submitted')

    # ### end Alembic commands ###
